all:
  children:
    bootnode-server:
      hosts:  
       bootnode-server:
          ansible_host: 139.59.73.20
          ansible_ssh_user: root 
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

      vars:
             backup_dir: "/root/backup"
             aws_bucket: "backup-devnet-bootnode"
             directories_to_backup:
             - { name: "bg-node1", path: "/root/bg-node1" }
             - { name: "bg-node2", path: "/root/bg-node2" }
             - { name: "bg-node3", path: "/root/bg-node3" }
             - { name: "bg-node4", path: "/root/bg-node4" }
             - { name: "bootnode", path: "/root/bootnode" }                                