version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: "develop"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: github-actions
    directory: /
    target-branch: "develop"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"