image: docker:latest

cache:
  key: one-key-to-rule-them-all

stages:
  - lint
  - build
  - deploy

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

golangci-lint:
    image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
    stage: lint
    extends: .go-cache
    allow_failure: true
    script:
      # Use default .golangci.yml file from the image if one is not present in the project root.
      - '[ -e .golangci.yml ] || cp /golangci/.golangci.yml .'
      # remove `--issues-exit-code 0` or set to non-zero to fail the job if linting issues are detected
      - golangci-lint run -E whitespace -E wsl -E wastedassign -E unconvert -E tparallel -E thelper -E stylecheck -E prealloc -E predeclared -E nlreturn -E misspell -E makezero -E lll -E importas -E ifshort -E gosec -E  gofmt -E goconst -E forcetypeassert -E dogsled -E dupl -E errname -E errorlint -E nolintlint --issues-exit-code 0 --out-format code-climate | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'

deploy-testnet:
  only:
    - develop
  image: alpine:latest
  stage: deploy
  script:
    - echo $CD_DEV_ID_RSA_149_102_155_207
    - chmod og= $CD_DEV_ID_RSA_149_102_155_207
    - chmod og= $CD_DEV_ID_RSA_66_94_122_24
    - chmod og= $CD_DEV_ID_RSA_86_48_23_194
    - chmod og= $CD_DEV_ID_RSA_207_244_228_225
    - chmod og= $CD_DEV_ID_RSA_45_140_185_105

    - apk update && apk add openssh-client

    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "rm -f ~/moichain && rm -rf ~/moichain_repo"
    - scp -i $CD_DEV_ID_RSA_149_102_155_207 -r . $CD_DEV_USER@$CD_DEV_IP_149_102_155_207:~/moichain_repo
    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "cd ~/moichain_repo && export CGO_CFLAGS='-O -D__BLST_PORTABLE__' && go build -o moichain"
    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "mv ~/moichain_repo/moichain ~/"
    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "pm2 delete all"
    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "cd ~/ && rm -rf test_* logs && mkdir logs"
    - ssh -i $CD_DEV_ID_RSA_149_102_155_207 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_149_102_155_207 "cd ~/ && bash moichain.sh $CD_DEV_PODS_COUNT"


    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "rm -f ~/moichain && rm -rf ~/moichain_repo"
    - scp -i $CD_DEV_ID_RSA_66_94_122_24 -r . $CD_DEV_USER@$CD_DEV_IP_66_94_122_24:~/moichain_repo
    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "cd ~/moichain_repo && export CGO_CFLAGS='-O -D__BLST_PORTABLE__' && go build -o moichain"
    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "mv ~/moichain_repo/moichain ~/"
    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "pm2 delete all"
    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "cd ~/ && rm -rf test_* logs && mkdir logs"
    - ssh -i $CD_DEV_ID_RSA_66_94_122_24 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_66_94_122_24 "cd ~/ && bash moichain.sh $CD_DEV_PODS_COUNT"


    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "rm -f ~/moichain && rm -rf ~/moichain_repo"
    - scp -i $CD_DEV_ID_RSA_86_48_23_194 -r . $CD_DEV_USER@$CD_DEV_IP_86_48_23_194:~/moichain_repo
    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "cd ~/moichain_repo && export CGO_CFLAGS='-O -D__BLST_PORTABLE__' && go build -o moichain"
    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "mv ~/moichain_repo/moichain ~/"
    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "pm2 delete all"
    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "cd ~/ && rm -rf test_* logs && mkdir logs"
    - ssh -i $CD_DEV_ID_RSA_86_48_23_194 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_86_48_23_194 "cd ~/ && bash moichain.sh $CD_DEV_PODS_COUNT"


    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "rm -f ~/moichain && rm -rf ~/moichain_repo"
    - scp -i $CD_DEV_ID_RSA_207_244_228_225 -r . $CD_DEV_USER@$CD_DEV_IP_207_244_228_225:~/moichain_repo
    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "cd ~/moichain_repo && export CGO_CFLAGS='-O -D__BLST_PORTABLE__' && go build -o moichain"
    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "mv ~/moichain_repo/moichain ~/"
    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "pm2 delete all"
    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "cd ~/ && rm -rf test_* logs && mkdir logs"
    - ssh -i $CD_DEV_ID_RSA_207_244_228_225 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_207_244_228_225 "cd ~/ && bash moichain.sh $CD_DEV_PODS_COUNT"

    
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "rm -f ~/moichain && rm -rf ~/moichain_repo"
    - scp -i $CD_DEV_ID_RSA_45_140_185_105 -r . $CD_DEV_USER@$CD_DEV_IP_45_140_185_105:~/moichain_repo
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "cd ~/moichain_repo && export CGO_CFLAGS='-O -D__BLST_PORTABLE__' && go build -o moichain"
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "mv ~/moichain_repo/moichain ~/"
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "pm2 delete all"
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "cd ~/ && rm -rf test_* logs && mkdir logs"
    - ssh -i $CD_DEV_ID_RSA_45_140_185_105 -o StrictHostKeyChecking=no $CD_DEV_USER@$CD_DEV_IP_45_140_185_105 "cd ~/ && bash moichain.sh $CD_DEV_PODS_COUNT"