package ktypes

import "errors"

var (
	ErrInvalidAddress              = errors.New("invalid address")
	ErrEmptyHash                   = errors.New("empty hash")
	ErrKeyNotFound                 = errors.New("key is not available")
	ErrDBCallFailed                = errors.New("db call failed")
	ErrDBInit                      = errors.New("db initiation failed")
	ErrUnderpriced                 = errors.New("transaction underpriced")
	ErrAccountNotFound             = errors.New("account not found")
	ErrPublicKeyNotFound           = errors.New("public key not found")
	ErrRPCFailed                   = errors.New("unable to initiate rpc")
	ErrHandlersFailed              = errors.New("unable to initiate sub handlers")
	ErrGenesisSetupFailed          = errors.New("genesis setup failed")
	ErrTimeOut                     = errors.New("timeout")
	ErrSlotsFull                   = errors.New("slots not available")
	ErrContextStateNotFound        = errors.New("context state not found")
	ErrHashMismatch                = errors.New("hash mismatch")
	ErrExecutionFailed             = errors.New("execution failed")
	ErrStateNotFound               = errors.New("state not found")
	ErrObjectNotFound              = errors.New("unable to fetch state object")
	ErrInvalidKramaID              = errors.New("invalid krama id")
	ErrParsingCID                  = errors.New("error parsing cid")
	ErrNetworkFetchFailed          = errors.New("unable to fetch the cid")
	ErrDBInsertFailed              = errors.New("db insert failed")
	ErrKeyExists                   = errors.New("key already exists")
	ErrCommitFailed                = errors.New("unable to commit state object")
	ErrContextCreation             = errors.New("context creation failed")
	ErrUpdatingContext             = errors.New("unable to update context")
	ErrAssetCreation               = errors.New("asset creation failed")
	ErrUpdatingContextObject       = errors.New("unable to update context object ")
	ErrConflictingVote             = errors.New("conflicting vote")
	ErrKramaIDNotFound             = errors.New("krama id not found")
	ErrVaultInit                   = errors.New("vault initialization failed")
	ErrSignatureVerificationFailed = errors.New("invalid signatures")
	ErrInvalidBlockTime            = errors.New("invalid block time")
	ErrInvalidSeal                 = errors.New("invalid tesseract seal")
	ErrQuorumFailed                = errors.New("ics quorum conditions not met")
	ErrUpdatingInclusivity         = errors.New("failed updating node inclusivity")
	ErrReceiptNotFound             = errors.New("receipt not found")
	ErrInvalidInteractionType      = errors.New("invalid interaction type")
	ErrStorageEntryNotFound        = errors.New("storage entry not found")
	ErrFetchingStorageObject       = errors.New("error fetching storage object")
	ErrFetchingBalanceObject       = errors.New("error fetching balance object")
	ErrFetchingTesseract           = errors.New("error fetching tesseract")
	ErrInvalidNonce                = errors.New("invalid nonce")
	ErrAssetNotFound               = errors.New("asset not found")
	ErrInvalidInteractions         = errors.New("invalid interactions")
	ErrInvalidHeight               = errors.New("invalid height")
	ErrInterfaceConversion         = errors.New("type assertion failed")
	ErrInvalidAPI                  = errors.New("invalid api")
	ErrPeerNotAvailable            = errors.New("peer not available")
)
