---
#################################
## Docker stop on moi source server ( babylon-46 to babylon-90 ) #
#################################

- name: Run stop.sh on the moi source server
  hosts: moi-source-servers
  tasks:
    - name: Run stop.sh on moi source server
      import_tasks: common/stop.yaml
      vars:
        file_name: moipod_stop.sh
        owner: "{{ become_user }}"
        group: "{{ become_user }}"
        mode: '0755'
      become_user: "{{ become_user }}"

#################################
## Docker stop on moi destination server ( babylon-01 to babylon-45 ) #
#################################

- name: Run stop.sh on the moi source server
  hosts: moi-destination-servers
  tasks:
    - name: Run stop.sh on moi source server
      import_tasks: common/stop.yaml
      vars:
        file_name: moipod_stop.sh
        owner: "{{ become_user }}"
        group: "{{ become_user }}"
        mode: '0755'
      become_user: "{{ become_user }}"

###################################
# Docker stop on bootnode servers #
###################################

- name: Run bootnode_stop.sh on the bootnode servers
  hosts: bootnode-server
  gather_facts: false    
  tasks:
    - name: Run bootnode_stop.sh on bootnode servers
      include_tasks: common/stop.yaml
      vars:
        file_name: bootnode_stop.sh
        owner: root
        group: root
        mode: '0755'
        become_user: root

#################################
## Copy test directories from source ( babylon-46 to babylon-90 ) to teleport  #
#################################

- name: Copy test directories from source to teleport
  hosts: moi-source-servers
  gather_facts: false
  tasks:
    - name: Create directory on teleport to store test directories
      file:
        path: "/home/github/babylon-migration/{{ inventory_hostname }}"
        state: directory
        owner: github
        group: github
        mode: '0755'
      delegate_to: localhost
      run_once: false

    - name: Copy test directories from source server to teleport
      synchronize:
        src: "/home/moipod/shared/moipod/{{ item }}/"
        dest: "/home/github/babylon-migration/{{ inventory_hostname }}/{{ item }}/"
        mode: pull
        archive: yes
        rsync_opts:
          - "--chmod=755"       
      with_items:
        - test_0
        - test_1
        - test_2

#################################
## Copy and rename test directories from teleport to destination ( babylon-01 to babylon-45 ) #
#################################

- name: Copy and rename test directories from teleport to destination
  hosts: moi-destination-servers
  gather_facts: false
  vars:
    source_dest_map:
      babylon-node-01: babylon-node-46
      babylon-node-02: babylon-node-47
      babylon-node-03: babylon-node-48  
      babylon-node-04: babylon-node-49
      babylon-node-05: babylon-node-50
      babylon-node-06: babylon-node-51  
      babylon-node-07: babylon-node-52
      babylon-node-08: babylon-node-53
      babylon-node-09: babylon-node-54  
      babylon-node-10: babylon-node-55
      babylon-node-11: babylon-node-56
      babylon-node-12: babylon-node-57  
      babylon-node-13: babylon-node-58
      babylon-node-14: babylon-node-59
      babylon-node-15: babylon-node-60  
      babylon-node-16: babylon-node-61
      babylon-node-17: babylon-node-62
      babylon-node-18: babylon-node-63  
      babylon-node-19: babylon-node-64
      babylon-node-20: babylon-node-65
      babylon-node-21: babylon-node-66  
      babylon-node-22: babylon-node-67
      babylon-node-23: babylon-node-68
      babylon-node-24: babylon-node-69  
      babylon-node-25: babylon-node-70
      babylon-node-26: babylon-node-71
      babylon-node-27: babylon-node-72  
      babylon-node-28: babylon-node-73
      babylon-node-29: babylon-node-74
      babylon-node-30: babylon-node-75        
      babylon-node-31: babylon-node-76
      babylon-node-32: babylon-node-77
      babylon-node-33: babylon-node-78  
      babylon-node-34: babylon-node-79
      babylon-node-35: babylon-node-80
      babylon-node-36: babylon-node-81  
      babylon-node-37: babylon-node-82
      babylon-node-38: babylon-node-83
      babylon-node-39: babylon-node-84  
      babylon-node-40: babylon-node-85
      babylon-node-41: babylon-node-86
      babylon-node-42: babylon-node-87  
      babylon-node-43: babylon-node-88
      babylon-node-44: babylon-node-89
      babylon-node-45: babylon-node-90                                                         
    source_host: "{{ source_dest_map[inventory_hostname] }}"
    test_map:
      test_0: test_3
      test_1: test_4
      test_2: test_5

  tasks:
    - name: Copy test directories from jump server to destination server
      copy:
        src: "/home/github/babylon-migration/{{ source_host }}/{{ item.key }}/"
        dest: "/home/moipod/shared/moipod/{{ item.value }}/"
        mode: "0755"
      with_dict: "{{ test_map }}"

    - name: Set permissions and ownership on copied directories
      file:
        path: "/home/moipod/shared/moipod/{{ item.value }}"
        owner: moipod
        group: moipod
        mode: "0755"
        state: directory
      with_dict: "{{ test_map }}"

#########################################
# update config file on moi destination server ( babylon-01 to babylon-45 ) #
#########################################

- name: Update config.json file on moi servers
  hosts: moi-destination-servers
  become: true
  become_user: "{{ become_user }}"
  vars:
    local_template_path: "/tmp/config_template.json.j2"

  tasks:
  - name: Copy template from jump server to target server
    copy:
      src: "{{ local_template_path }}"
      dest: "/tmp/config_template.json.j2"
      mode: "0644"

  - name: Generate config.json files using the fetched template
    template:
      src: "/tmp/config_template.json.j2"
      dest: "/home/{{ app_user }}/shared/moipod/test_{{ item }}/config.json"
      mode: "0644"
    loop: "{{ range(0, hostvars[inventory_hostname].no_of_pods) | list }}"
    loop_control:
      loop_var: item
    vars:
      inventory_type: "{{ hostvars[inventory_hostname].inventory_type }}"
      node_port: "{{ base_port + item }}"
      prometheus_port: "{{ base_prometheus_port + item }}"
      jsonrpc_port: "{{ base_jsonrpc_port + item }}"

###############################################
## Copy instances.json from source to teleport
###############################################

- name: Copy instances.json from source servers to teleport
  hosts: moi-source-servers
  gather_facts: false
  tasks:
    - name: Create directory on teleport to store instances.json
      file:
        path: "/home/github/babylon-migration/{{ inventory_hostname }}"
        state: directory
        owner: github
        group: github
        mode: '0755'
      delegate_to: localhost
      run_once: false

    - name: Copy instances.json from source to teleport
      fetch:
        src: "/home/moipod/shared/moipod/instances.json"
        dest: "/home/github/babylon-migration/{{ inventory_hostname }}/instances.json"
        flat: yes

#####################################################################
## Update rpc_url and append to destination's instances.json file
#####################################################################

- name: Update rpc_url and append to destination
  hosts: moi-destination-servers
  gather_facts: false
  vars:
    teleport_base: "/home/github/babylon-migration"
    port_base: 1603
    source_dest_map:
      babylon-node-01: babylon-node-46
      babylon-node-02: babylon-node-47
      babylon-node-03: babylon-node-48    
      babylon-node-04: babylon-node-49
      babylon-node-05: babylon-node-50
      babylon-node-06: babylon-node-51  
      babylon-node-07: babylon-node-52
      babylon-node-08: babylon-node-53
      babylon-node-09: babylon-node-54  
      babylon-node-10: babylon-node-55
      babylon-node-11: babylon-node-56
      babylon-node-12: babylon-node-57  
      babylon-node-13: babylon-node-58
      babylon-node-14: babylon-node-59
      babylon-node-15: babylon-node-60  
      babylon-node-16: babylon-node-61
      babylon-node-17: babylon-node-62
      babylon-node-18: babylon-node-63  
      babylon-node-19: babylon-node-64
      babylon-node-20: babylon-node-65
      babylon-node-21: babylon-node-66  
      babylon-node-22: babylon-node-67
      babylon-node-23: babylon-node-68
      babylon-node-24: babylon-node-69  
      babylon-node-25: babylon-node-70
      babylon-node-26: babylon-node-71
      babylon-node-27: babylon-node-72  
      babylon-node-28: babylon-node-73
      babylon-node-29: babylon-node-74
      babylon-node-30: babylon-node-75        
      babylon-node-31: babylon-node-76
      babylon-node-32: babylon-node-77
      babylon-node-33: babylon-node-78  
      babylon-node-34: babylon-node-79
      babylon-node-35: babylon-node-80
      babylon-node-36: babylon-node-81  
      babylon-node-37: babylon-node-82
      babylon-node-38: babylon-node-83
      babylon-node-39: babylon-node-84  
      babylon-node-40: babylon-node-85
      babylon-node-41: babylon-node-86
      babylon-node-42: babylon-node-87  
      babylon-node-43: babylon-node-88
      babylon-node-44: babylon-node-89
      babylon-node-45: babylon-node-90           
  tasks:
    - name: Set source host for this destination node
      set_fact:
        source_host: "{{ source_dest_map[inventory_hostname] }}"

    - name: Read source instances.json from teleport
      delegate_to: localhost
      slurp:
        src: "{{ teleport_base }}/{{ source_host }}/instances.json"
      register: source_data

    - name: Decode and parse source instances.json
      set_fact:
        source_instances: "{{ source_data.content | b64decode | from_json }}"

    - name: Generate updated instances list with new rpc_url
      set_fact:
        updated_instances: "{{ updated_instances | default([]) + [ {
          'krama_id': item.0.krama_id,
          'rpc_url': ansible_host ~ ':' ~ item.1,
          'consensus_key': item.0.consensus_key
        } ] }}"
      loop: "{{ source_instances | zip(range(port_base, port_base + source_instances | length)) | list }}"
      loop_control:
        loop_var: item
        label: "{{ item.0.krama_id }}"


    - name: Fetch destination's existing instances.json
      slurp:
        src: "/home/moipod/shared/moipod/instances.json"
      register: dest_data

    - name: Merge destination and updated source entries
      set_fact:
        merged_instances_raw: "{{ (dest_data.content | b64decode | from_json) + updated_instances }}"

    - name: Write merged instances.json with ordered keys using template
      template:
        src: merged_instances.json.j2
        dest: "/home/moipod/shared/moipod/instances.json"
        mode: "0755"
        owner: moipod
        group: moipod

#################################################
# docker compose file update on moi destination server ( babylon-01 to babylon-45 ) #
#################################################

- name: Generate docker-compose.yaml file for destination moi server
  hosts: moi-destination-servers
  become: true
  become_user: "{{ become_user }}"
  tasks:
    - name: Create docker-compose.yaml from template
      template:
        src: "nodes-docker-compose-template.yaml.j2"
        dest: "/home/{{ app_user }}/stack/moipod/docker-compose.yml"

#################################################
# update docker compose file on bootnode #
#################################################

- name: Generate docker-compose.yml file for bootnode
  hosts: bootnode-server
  become: true
  become_user: "{{ become_user }}"
  tasks:
    - name: Backup the existing docker-compose.yml file
      become_user: "{{ become_user }}"
      copy:
        src: "/home/{{ app_user }}/stack/bootnode/docker-compose.yml"
        dest: "/home/{{ app_user }}/stack/bootnode/docker-compose.yml.bak"
        remote_src: true
    - name: Create docker-compose.yaml from template
      template:
        src: "bootnode-docker-compose-template.yaml.j2"
        dest: "/home/{{ app_user }}/stack/bootnode/docker-compose.yml"

#####################################
# Docker start on bootnode server 1  #
#####################################

- name: Run bootnode_start.sh on the bootnode servers
  hosts: babylon-bootnode-server
  gather_facts: false  
  tasks:
  - name: Run bootnode_start.sh on bootnode servers
    include_tasks: common/start.yaml
    vars:
      file_name: bootnode_start.sh
      owner: root
      group: root
      mode: '0755'
      become_user: root

#####################################
# Docker start on bootnode server 2  #
#####################################

- name: Run bootnode_start.sh on the bootnode servers
  hosts: babylon-bootnode-extra-server
  gather_facts: false  
  tasks:
  - name: Run bootnode_start.sh on bootnode servers
    include_tasks: common/start.yaml
    vars:
      file_name: bootnode_start.sh
      owner: root
      group: root
      mode: '0755'
      become_user: root

#####################################
# Docker Restart on bootnode server 1  #
#####################################

- name: Run bootnode_restart.sh on the bootnode servers
  hosts: babylon-bootnode-server
  gather_facts: false  
  tasks:
  - name: Run bootnode_restart.sh on bootnode servers
    include_tasks: common/restart.yaml
    vars:
      file_name: bootnode_restart.sh
      owner: root
      group: root
      mode: '0755'
      become_user: root

##################################
# Docker start on destination moi server ( babylon-01 to babylon-45 ) #
##################################

- name: Run moipod_start.sh on the moi server
  hosts: moi-destination-servers
  tasks:
  - name: Run moipod_start.sh on moi server
    import_tasks: common/start.yaml
    vars:
      file_name: moipod_start.sh
      owner: "{{ become_user }}"
      group: "{{ become_user }}"
      mode: '0755'
    become_user: "{{ become_user }}"
