---
- name: Set timestamp
  hosts: all
  gather_facts: false
  tasks:
    - name: Set timestamp as a fact
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H') }}"
    - name: Echo the timestamp
      debug:
        msg: "The timestamp is: {{ timestamp }}"

###########################################################
# Ensure AWS CLI is installed on all hosts
###########################################################

- name: Ensure AWS CLI is installed on all hosts
  hosts: all
  gather_facts: true
  tasks:    
  - name: Ensure AWS CLI is installed on all bootnode servers
    include_tasks: common/install_aws_cli.yaml

###################################
# Docker stop on bootnode servers #
###################################

- name: Run bootnode_stop.sh on the bootnode servers
  hosts: all
  gather_facts: false    
  tasks:
    - name: Run bootnode_stop.sh on bootnode servers
      include_tasks: common/stop.yaml
      vars:
        file_name: bootnode_stop.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        become_user: ubuntu

######################################################
## Backup folder on bootnode server and upload to s3 #
######################################################

- name: Backup folder on bootnode servers and upload to S3
  hosts: all
  gather_facts: true
  tasks:
  - name: Ensure backup directory exists
    file:
      path: "{{ backup_dir }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0755'
      
  - name: Backup all directories into a single tar file
    ignore_errors: yes
    command: >
      tar czf {{ backup_dir }}/backup_{{ inventory_hostname }}_{{ timestamp }}.tar.gz
      {{ directories_to_backup | map(attribute='path') | join(' ') }}

  - name: Check if the tar file exists before uploading to S3
    become_user: ubuntu
    stat:
      path: "{{ backup_dir }}/backup_{{ inventory_hostname }}_{{ timestamp }}.tar.gz"
    register: tar_file_stat

  - name: Upload the backup tar file to S3
    ignore_errors: yes
    command: >
      aws s3 cp {{ backup_dir }}/backup_{{ inventory_hostname }}_{{ timestamp }}.tar.gz
      s3://{{ aws_bucket }}/{{ group_names[0] }}-backup/{{ inventory_hostname }}/{{ timestamp }}/backup_{{ inventory_hostname }}_{{ timestamp }}.tar.gz
    environment:
      AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"

#################################################
# update docker compose file on bootnode #
#################################################

- name: Generate docker-compose.yml file for bootnode
  hosts: all
  become: true
  become_user: ubuntu
  tasks:
    - name: Backup the existing docker-compose.yml file
      become_user: ubuntu
      copy:
        src: "/home/ubuntu/stack/bootnode/docker-compose.yml"
        dest: "/home/ubuntu/stack/bootnode/docker-compose.yml.bak"
        remote_src: true
    - name: Create docker-compose.yaml from template
      template:
        src: "bootnode-docker-compose-template.yaml.j2"
        dest: "/home/ubuntu/stack/bootnode/docker-compose.yml"

#################################
# Docker login on bootnode servers #
#################################

- name: Login to GHCR on bootnode servers
  hosts: all
  become: yes
  become_user: ubuntu
  tasks:

    - name: Logout from GHCR
      shell: docker --config /home/ubuntu/.docker logout ghcr.io
      ignore_errors: yes
      environment:
        HOME: "/home/ubuntu"

    - name: Login to GHCR using Docker
      shell: |
        echo "{{ ghcr_pat }}" | docker --config /home/ubuntu/.docker login ghcr.io -u {{ ghcr_user }} --password-stdin
      no_log: true
      environment:
        HOME: "/home/ubuntu"

#####################################
# Docker start on bootnode servers  #
#####################################

- name: Run bootnode_start.sh on the bootnode servers
  hosts: all
  gather_facts: false  
  tasks:
  - name: Run bootnode_start.sh on bootnode servers
    include_tasks: common/start.yaml
    vars:
      file_name: bootnode_start.sh
      owner: ubuntu
      group: ubuntu
      mode: '0755'
      become_user: ubuntu
