package ecdsa

import (
	"github.com/libp2p/go-libp2p-core/crypto"
	"gitlab.com/sarvalabs/moichain/mudra/common"
	"gitlab.com/sarvalabs/moichain/mudra/kramaid"
)

// EcdsaSecp256k1Signature is a custom type of Signature that uses Secp256k1 Curve and ECDSA signing
// algorithm for signing also implements Mudra interface
type EcdsaSecp256k1Signature common.Signature

// Type returns ECDSA_SECP256K1 type
func (s256Sig *EcdsaSecp256k1Signature) Type() common.SigType {
	return common.EcdsaSecp256k1
}

// Sign the data using Secp256k1 curve
func (s256Sig *EcdsaSecp256k1Signature) Sign(data []byte, signingKey []byte, kid kramaid.KramaID) error {
	nodePrivKey, err := crypto.UnmarshalSecp256k1PrivateKey(signingKey)
	if err != nil {
		return err
	}

	// below sigBytes is generated by signing given data with secp256k1 type private key
	sigBytes, err := nodePrivKey.Sign(data)
	if err != nil {
		return err
	}

	var sigPrefix [2]byte
	sigPrefix[0] = common.EcdsaSecp256k1.Byte()
	sigPrefix[1] = byte(len(sigBytes))
	s256Sig.SigPrefix = sigPrefix
	s256Sig.Digest = sigBytes

	ver, err := kid.Version()
	if err != nil {
		return err
	}

	if ver == 1 {
		s256Sig.Extra = nil // EcdsaSecp256k1Signature does not need any extra bytes if kramaid version is 1
	} else {
		s256Sig.Extra, err = nodePrivKey.GetPublic().Raw()
		if err != nil {
			return err
		}
	}

	return nil
}

// Verify used to verify signature against the publicKey
func (s256Sig *EcdsaSecp256k1Signature) Verify(message []byte, nodePublicKey []byte) (bool, error) {
	pubKey, err := crypto.UnmarshalSecp256k1PublicKey(nodePublicKey)
	if err != nil {
		return false, err
	}

	return pubKey.Verify(message, s256Sig.Digest)
}
