syntax: 0.1.0
engine:
  kind: PISA
  flags: []
elements:
  - ptr: 0
    deps: []
    kind: state
    data:
      kind: persistent
      fields:
        - slot: 0
          label: name
          type: string
        - slot: 1
          label: symbol
          type: string
        - slot: 2
          label: supply
          type: u64
        - slot: 3
          label: balances
          type: map[address]u64
        - slot: 4
          label: allowances
          type: map[address]map[address]u64
  - ptr: 1
    deps:
      - 0
    kind: routine
    data:
      name: Seeder!
      kind: deployer
      accepts:
        - slot: 0
          label: name
          type: string
        - slot: 1
          label: symbol
          type: string
        - slot: 2
          label: supply
          type: u64
        - slot: 3
          label: seeder
          type: address
      returns: []
      executes:
        bin: []
        hex: ""
        asm:
          - OBTAIN $0 &0
          - PSAVE $0 &0
          - OBTAIN $0 &1
          - PSAVE $0 &1
          - OBTAIN $0 &2
          - PSAVE $0 &2
          - PLOAD $1 &3
          - OBTAIN $2 &3
          - SETIDX $1 $2 $0
          - PSAVE $1 &3
      catches: []
  - ptr: 2
    deps: []
    kind: constant
    data:
      type: u64
      value: "0x030a"
  - ptr: 3
    deps: []
    kind: typedef
    data: map[address]u64
  - ptr: 4
    deps:
      - 0
    kind: routine
    data:
      name: Name
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: name
          type: string
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &0
          - YIELD $0 &0
      catches: []
  - ptr: 5
    deps:
      - 0
    kind: routine
    data:
      name: Symbol
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: symbol
          type: string
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &1
          - YIELD $0 &0
      catches: []
  - ptr: 6
    deps:
      - 0
    kind: routine
    data:
      name: Decimals
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: decimals
          type: u64
      executes:
        bin: []
        hex: ""
        asm:
          - LDPTR1 $0 0x2
          - CONST $0 $0
          - YIELD $0 &0
      catches: []
  - ptr: 7
    deps:
      - 0
    kind: routine
    data:
      name: TotalSupply
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: supply
          type: u64
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &2
          - YIELD $0 &0
      catches: []
  - ptr: 8
    deps:
      - 0
    kind: routine
    data:
      name: BalanceOf
      kind: invokable
      accepts:
        - slot: 0
          label: addr
          type: address
      returns:
        - slot: 0
          label: balance
          type: u64
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &3
          - OBTAIN $1 &0
          - GETIDX $2 $0 $1
          - YIELD $2 &0
      catches: []
  - ptr: 9
    deps:
      - 0
    kind: routine
    data:
      name: Allowance
      kind: invokable
      accepts:
        - slot: 0
          label: owner
          type: address
        - slot: 1
          label: spender
          type: address
      returns:
        - slot: 0
          label: allowance
          type: u64
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &4
          - OBTAIN $1 &0
          - GETIDX $2 $0 $1
          - OBTAIN $3 &1
          - GETIDX $4 $2 $3
          - YIELD $4 &0
      catches: []
  - ptr: 10
    deps:
      - 0
      - 3
    kind: routine
    data:
      name: Approve!
      kind: invokable
      accepts:
        - slot: 0
          label: owner
          type: address
        - slot: 1
          label: spender
          type: address
        - slot: 2
          label: amount
          type: u64
      returns:
        - slot: 0
          label: ok
          type: bool
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &4
          - OBTAIN $1 &0
          - GETIDX $2 $0 $1
          - ISNULL $3 $2
          - NOT $3 $3
          - LDPTR1 $4 0xA
          - JUMPI $4 $3
          - LDPTR1 $4 0x0
          - MAKE $4 0x4
          - COPY $2 $4
          - DEST
          - OBTAIN $3 &1
          - OBTAIN $4 &2
          - SETIDX $2 $3 $4
          - SETIDX $0 $1 $2
          - PSAVE $0 &4
          - PMAKE $0 0x1
          - NOT $0 $0
          - YIELD $0 &0
      catches: []
  - ptr: 11
    deps:
      - 0
    kind: routine
    data:
      name: Transfer!
      kind: invokable
      accepts:
        - slot: 0
          label: from
          type: address
        - slot: 1
          label: to
          type: address
        - slot: 2
          label: amount
          type: u64
      returns:
        - slot: 0
          label: ok
          type: bool
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &3
          - OBTAIN $1 &0
          - GETIDX $2 $0 $1
          - OBTAIN $3 &2
          - LT $4 $3 $2
          - LDPTR1 $5 0xA
          - JUMPI $5 $4
          - PMAKE $0 0x1
          - YIELD $0 &0
          - TERM
          - DEST
          - SUB $4 $2 $3
          - SETIDX $0 $1 $4
          - OBTAIN $5 &1
          - GETIDX $4 $0 $5
          - ADD $6 $4 $3
          - SETIDX $0 $5 $6
          - PSAVE $0 &3
          - PMAKE $0 0x1
          - NOT $0 $0
          - YIELD $0 &0
      catches: []
  - ptr: 12
    deps:
      - 0
    kind: routine
    data:
      name: Mint!
      kind: invokable
      accepts:
        - slot: 0
          label: amount
          type: u64
        - slot: 1
          label: addr
          type: address
      returns:
        - slot: 0
          label: ok
          type: bool
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &2
          - OBTAIN $1 &0
          - ADD $0 $0 $1
          - PSAVE $0 &2
          - PLOAD $0 &3
          - OBTAIN $2 &1
          - GETIDX $3 $0 $2
          - ADD $3 $3 $1
          - SETIDX $0 $2 $3
          - PSAVE $0 &3
          - PMAKE $0 0x1
          - NOT $0 $0
          - YIELD $0 &0
      catches: []
  - ptr: 13
    deps:
      - 0
    kind: routine
    data:
      name: Burn!
      kind: invokable
      accepts:
        - slot: 0
          label: amount
          type: u64
        - slot: 1
          label: addr
          type: address
      returns:
        - slot: 0
          label: ok
          type: bool
      executes:
        bin: []
        hex: ""
        asm:
          - PLOAD $0 &3
          - OBTAIN $1 &1
          - GETIDX $2 $0 $1
          - OBTAIN $3 &0
          - LT $4 $3 $2
          - LDPTR1 $5 0xA
          - JUMPI $5 $4
          - PMAKE $0 0x1
          - YIELD $0 &0
          - TERM
          - DEST
          - SUB $4 $2 $3
          - SETIDX $0 $1 $4
          - PSAVE $0 &3
          - PLOAD $0 &2
          - SUB $0 $0 $3
          - PSAVE $0 &2
          - PMAKE $0 0x1
          - NOT $0 $0
          - YIELD $0 &0
      catches: []