syntax: 1
engine:
  kind: PISA
  flags: []
elements:
  - ptr: 0
    kind: constant
    data:
      type: u64
      value: '0x0302'
  - ptr: 1
    kind: constant
    data:
      type: string
      value: 0x067a65726f206164647265737320666f722073656e646572
  - ptr: 2
    kind: constant
    data:
      type: string
      value: 0x067a65726f206164647265737320666f72207265636569766572
  - ptr: 3
    kind: constant
    data:
      type: string
      value: 0x06696e73756666696369656e742062616c616e636520666f722073656e646572
  - ptr: 4
    kind: constant
    data:
      type: string
      value: 0x06696e73756666696369656e742062616c616e636520666f72206275726e
  - ptr: 5
    kind: typedef
    data: map[address]u256
  - ptr: 6
    kind: state
    data:
      mode: persistent
      fields:
        - slot: 0
          label: symbol
          type: string
        - slot: 1
          label: supply
          type: u256
        - slot: 2
          label: balances
          type: map[address]u256
  - ptr: 7
    deps:
      - 6
    kind: routine
    data:
      name: Seeder
      mode: persistent
      kind: deployer
      accepts:
        - slot: 0
          label: symbol
          type: string
        - slot: 1
          label: supply
          type: u256
      returns: []
      executes:
        asm:
          - PLOAD $0 &0
          - OBTAIN $1 &0
          - DISPERSE $0 $1
          - PSAVE $0
          - PLOAD $0 &1
          - OBTAIN $1 &1
          - DISPERSE $0 $1
          - PSAVE $0
          - PLOAD $0 &2
          - SENDER $2
          - ADDR $2 $2
          - SETKEY $0 $2 $1
          - PSAVE $0
      catches: []
  - ptr: 8
    deps:
      - 6
    kind: routine
    data:
      name: Symbol
      mode: readonly
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: symbol
          type: string
      executes:
        asm:
          - PLOAD $0 &0
          - YIELD $0 &0
          - PFREE $0
      catches: []
  - ptr: 9
    deps:
      - 0
    kind: routine
    data:
      name: Decimals
      mode: readonly
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: decimals
          type: u64
      executes:
        asm:
          - LDPTR1 $0 0x0
          - CONST $0 $0
          - YIELD $0 &0
      catches: []
  - ptr: 10
    deps:
      - 6
    kind: routine
    data:
      name: TotalSupply
      mode: readonly
      kind: invokable
      accepts: []
      returns:
        - slot: 0
          label: supply
          type: u256
      executes:
        asm:
          - PLOAD $0 &1
          - YIELD $0 &0
          - PFREE $0
      catches: []
  - ptr: 11
    deps:
      - 6
    kind: routine
    data:
      name: BalanceOf
      mode: readonly
      kind: invokable
      accepts:
        - slot: 0
          label: address
          type: address
      returns:
        - slot: 0
          label: balance
          type: u256
      executes:
        asm:
          - PLOAD $0 &2
          - OBTAIN $1 &0
          - GENKEY $1 $0 $1
          - YIELD $1 &0
          - PFREE $0
      catches: []
  - ptr: 12
    deps:
      - 1
      - 2
      - 3
      - 6
    kind: routine
    data:
      name: Transfer
      mode: persistent
      kind: invokable
      accepts:
        - slot: 0
          label: receiver
          type: address
        - slot: 1
          label: amount
          type: u256
      returns: []
      executes:
        asm:
          - SENDER $0
          - ADDR $0 $0
          - BOOL $1 $0
          - LDPTR1 $2 0x8
          - JUMPI $2 $1
          - LDPTR1 $1 0x1
          - CONST $1 $1
          - THROW $1
          - DEST
          - OBTAIN $1 &0
          - BOOL $2 $1
          - LDPTR1 $3 0x10
          - JUMPI $3 $2
          - LDPTR1 $2 0x2
          - CONST $2 $2
          - THROW $2
          - DEST
          - PLOAD $2 &2
          - GENKEY $3 $2 $0
          - OBTAIN $4 &1
          - LT $5 $3 $4
          - NOT $5 $5
          - LDPTR1 $6 0x1b
          - JUMPI $6 $5
          - LDPTR1 $5 0x3
          - CONST $5 $5
          - THROW $5
          - DEST
          - SUB $3 $3 $4
          - SETKEY $2 $0 $3
          - GENKEY $0 $2 $1
          - ADD $0 $0 $4
          - SETKEY $2 $1 $0
          - PSAVE $2
      catches: []
  - ptr: 13
    deps:
      - 6
    kind: routine
    data:
      name: Mint
      mode: persistent
      kind: invokable
      accepts:
        - slot: 0
          label: amount
          type: u256
      returns: []
      executes:
        asm:
          - SENDER $0
          - ADDR $0 $0
          - PLOAD $1 &1
          - GATHER $2 $1
          - OBTAIN $3 &0
          - ADD $2 $2 $3
          - DISPERSE $1 $2
          - PSAVE $1
          - PLOAD $1 &2
          - GENKEY $2 $1 $0
          - OBTAIN $3 &0
          - ADD $2 $2 $3
          - SETKEY $1 $0 $2
          - PSAVE $1
      catches: []
  - ptr: 14
    deps:
      - 4
      - 6
    kind: routine
    data:
      name: Burn
      mode: persistent
      kind: invokable
      accepts:
        - slot: 0
          label: amount
          type: u256
      returns: []
      executes:
        asm:
          - SENDER $0
          - ADDR $0 $0
          - PLOAD $1 &2
          - GENKEY $2 $1 $0
          - OBTAIN $3 &0
          - LT $4 $2 $3
          - NOT $4 $4
          - LDPTR1 $5 0xc
          - JUMPI $5 $4
          - LDPTR1 $4 0x4
          - CONST $4 $4
          - THROW $4
          - DEST
          - SUB $2 $2 $3
          - SETKEY $1 $0 $2
          - PSAVE $1
          - PLOAD $0 &1
          - GATHER $1 $0
          - OBTAIN $2 &0
          - SUB $2 $1 $2
          - COPY $1 $2
          - DISPERSE $0 $1
          - PSAVE $0
      catches: []
