syntax  : 0.1.0
engine  :
  kind : PISA
  flags: [ ]

elements:
  - ptr : 0
    kind: constant
    data:
      type : string
      value: 0x0668656c6c6f21

  - ptr : 1
    kind: constant
    data:
      type : uint64
      value: 0x0301

  - ptr : 2
    kind: routine
    data:
      name    : GetThrownError
      kind    : invokable
      executes:
        bin: [
          0x11, 0x00, 0x00, # ldptr1 $0 0x0
          0x10, 0x00, 0x00, # const $0 $0
          0x41, 0x00,       # throw $0
        ]

  - ptr : 3
    kind: routine
    data:
      name    : GetSystemError
      kind    : invokable
      accepts :
        - slot : 0
          label: a
          type : string
        - slot : 1
          label: b
          type : string
      executes:
        bin: [
          0x04, 0x00, 0x00,        # obtain $0 &0
          0x04, 0x01, 0x01,        # obtain $1 &1
          0x65, 0x02, 0x01, 0x00,  # add $2 $1 $0
        ]

  - ptr : 4
    kind: routine
    data:
      name    : GetOverflowError
      kind    : invokable
      accepts :
        - slot : 0
          label: value
          type : uint64
      executes:
        bin: [
          0x04, 0x00, 0x00,       # obtain $0 &0
          0x11, 0x01, 0x01,       # ldptr1 $1 0x1
          0x10, 0x01, 0x01,       # const $1 $1
          0x65, 0x01, 0x00, 0x01, # add $1 $0 $1
          0x66, 0x02, 0x00, 0x01, # sub $2 $0 $1
        ]

  - ptr : 5
    kind: constant
    data:
      type : string
      value: 0x066661696c656421

  - ptr : 6
    kind: routine
    data:
      name    : GetConditionalError
      kind    : invokable
      accepts :
        - slot : 0
          label: fail
          type : bool
      executes:
        bin: [
          0x04, 0x00, 0x00,   # obtain $0 &0
          0x11, 0x01, 0x07,   # ldptr1 $1 0x7
          0x62, 0x00, 0x00,   # not $0 $0
          0x03, 0x01, 0x00,   # jumpi $1 $0
          0x11, 0x02, 0x05,   # ldptr1 $2 0x5
          0x10, 0x02, 0x02,   # const $2 $2
          0x41, 0x02,         # throw $2
          0x01,               # dest
        ]