syntax  : 0.1.0
engine  :
  kind : PISA
  flags: [ ]

elements:
  - ptr : 0
    kind: state
    deps: [ 1 ]
    data:
      kind  : persistent
      fields:
        - slot : 0
          label: registry
          type : map[string]Person

  - ptr : 1
    kind: class
    data:
      name  : Person
      fields:
        - slot : 0
          label: name
          type : string
        - slot : 1
          label: age
          type : u64
        - slot : 2
          label: gender
          type : string

  - ptr : 2
    kind: routine
    deps: [ 0, 1 ]
    data:
      name    : StorePerson!
      kind    : invokable
      accepts :
        - slot : 0
          label: person
          type : Person
      executes:
        bin: [
          0x04, 0x00, 0x00,         # obtain $0 &0
          0x51, 0x01, 0x00, 0x00,   # getfld $1 $0 &0
          0x80, 0x02, 0x00,         # pload $2 &0
          0x54, 0x02, 0x01, 0x00,   # setidx $2 $1 $0
          0x81, 0x02, 0x00,         # psave $2 &0
        ]

  - ptr : 3
    kind: routine
    deps: [ 0, 1 ]
    data:
      name    : GetPerson
      kind    : invokable
      accepts :
        - slot : 0
          label: name
          type : string
      returns :
        - slot : 0
          label: person
          type : Person
      executes:
        bin: [
          0x80, 0x00, 0x00,         # pload $0 &0
          0x04, 0x01, 0x00,         # obtain $1 &0
          0x53, 0x02, 0x00, 0x01,   # getidx $2 $0 $1
          0x05, 0x02, 0x00,         # yield $2 &0
        ]

  - ptr : 4
    kind: routine
    deps: [ 1 ]
    data:
      name    : GetNameOf
      kind    : invokable
      accepts :
        - slot : 0
          label: person
          type : Person
      returns :
        - slot : 0
          label: name
          type : string
      executes:
        bin: [
          0x04, 0x00, 0x00,         # obtain $0 &0
          0x51, 0x01, 0x00, 0x00,   # getfld $1 $0 &0
          0x05, 0x01, 0x00,         # yield $1 &0
        ]

  - ptr : 5
    kind: routine
    deps: [ 1 ]
    data:
      name    : DoubleAge
      kind    : invokable
      accepts :
        - slot : 0
          label: person
          type : Person
      returns :
        - slot : 0
          label: person
          type : Person
      executes:
        bin: [
          0x04, 0x00, 0x00,         # obtain $0 &0
          0x51, 0x01, 0x00, 0x01,   # getfld $1 $0 &1
          0x24, 0x02, 0x01,         # copy $2 $1
          0x65, 0x02, 0x02, 0x01,   # add $2 $2 $1
          0x52, 0x00, 0x01, 0x02,   # setfld $0 &1 $2
          0x05, 0x00, 0x00,         # yield $0 &0
        ]

