name: Babylon Migration from 90 to 45 nodes
on:

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Specify the image/release tag"
        required: true
        default: "latest"      
     

env: 
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Connect to the jump server and execute the playbook
      - name: Run Ansible Playbook on Jump Server
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        with:
          host: ${{ secrets.BABYLON_NETWORK_UPGRADE_HOST }}
          username: ${{ secrets.BABYLON_NETWORK_UPGRADE_USER }}
          key: ${{ secrets.BABYLON_NETWORK_UPGRADE_PRIVATE_KEY }}
          port: ${{ secrets.BABYLON_NETWORK_UPGRADE_PORT }}
          command_timeout: 360m
          script: |
            echo "Starting playbook execution..."
            cd /home/github/go-moi
            echo ${{ github.ref_name }}
            echo "Pulling latest changes from branch: ${{ github.ref_name }}"
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            # Export AWS credentials as environment variables
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            aws s3 cp s3://babylon-migration-config-template/config_template.json.j2 /tmp/config_template.json.j2
            echo "${{ vars.BABYLON_MIGRATION_INVENTORY_FILE }}" | base64 -d > /tmp/node.yml
            cat /tmp/node.yml
            # Run the Ansible playbook with extra vars
            ansible-playbook -i /tmp/node.yml babylon-migration/network-upgrade.yaml -f 10 \
            --extra-vars "ansible_ssh_private_key_file=/home/github/.ssh/id_rsa" \
            -e "config_template_path=/tmp/config_template.json.j2 AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} SUDO_PASSWORD="" image_tag=${{ github.event.inputs.image_tag }}"
