name: Start/Stop Babylon Bootnode
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Specify the image/release tag"
        required: true
        default: "latest" 

env: 
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the actor is an admin
        id: check_permissions
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor,
            });
            const permission = response.data.permission;
            console.log(`Actor permission level: ${permission}`);
            core.setOutput("is_admin", permission === "admin");

    outputs:
      is_admin: ${{ steps.check_permissions.outputs.is_admin }}

  ansible-playbook:
    if: ${{ needs.check-permissions.outputs.is_admin == 'true' }}
    runs-on: ubuntu-latest
    needs: [check-permissions]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Connect to the jump server and execute the playbook
      - name: Run Ansible Playbook on Jump Server
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        with:
          host: ${{ secrets.BABYLON_NETWORK_UPGRADE_HOST }}
          username: ${{ secrets.BABYLON_NETWORK_UPGRADE_USER }}
          key: ${{ secrets.BABYLON_NETWORK_UPGRADE_PRIVATE_KEY }}
          port: ${{ secrets.BABYLON_NETWORK_UPGRADE_PORT }}
          script: |
            echo "Starting playbook execution..."
            cd /home/github/go-moi
            echo ${{ github.ref_name }}
            echo "Pulling latest changes from branch: ${{ github.ref_name }}"
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            # Export AWS credentials as environment variables
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            echo "${{ vars.BABYLON_BOOTNODE_INVENTORY_FILE }}" | base64 -d > /tmp/bootnode.yml
            cat /tmp/bootnode.yml            
            # Run the Ansible playbook with extra vars 
            ansible-playbook -i /tmp/bootnode.yml ansible-babylon/bootnode.yaml -f 10 \
            --extra-vars "ansible_ssh_private_key_file=/home/github/.ssh/id_rsa" \
            -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} image_tag=${{ github.event.inputs.image_tag }}"
