name: GO Deploy
on:
  push:
    branches:
      - develop

  workflow_dispatch: {}

jobs:
  ci:
    # if: github.event.pull_request.merged == true
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  stop:
    # if: github.event.pull_request.merged == true
    name: Stop Containers
    needs: ci
    uses: ./.github/workflows/stop.yml
    secrets:
      IP01: ${{ secrets.IP01 }}
      IP02: ${{ secrets.IP02 }}
      IP03: ${{ secrets.IP03 }}
      IP04: ${{ secrets.IP04 }}
      IP05: ${{ secrets.IP05 }}
      IP06: ${{ secrets.IP06 }}
      IP07: ${{ secrets.IP07 }}
      IP08: ${{ secrets.IP08 }}
      IP09: ${{ secrets.IP09 }}
      IP10: ${{ secrets.IP10 }}
      IP11: ${{ secrets.IP11 }}
      IP12: ${{ secrets.IP12 }}
      IP13: ${{ secrets.IP13 }}
      IP14: ${{ secrets.IP14 }}
      IP15: ${{ secrets.IP15 }}
      NODE_USER: ${{ secrets.NODE_USER }}
      TELEPORT_HOST: ${{ secrets.TELEPORT_HOST }}
      TELEPORT_USER: ${{ secrets.TELEPORT_USER }}
      TELEPORT_PRIVATE_KEY: ${{ secrets.TELEPORT_PRIVATE_KEY }}
      TELEPORT_PORT: ${{ secrets.TELEPORT_PORT }}

  cd:
    # if: github.event.pull_request.merged == true
    name: push to ghcr
    needs: stop
    uses: ./.github/workflows/ghcr.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  start:
    # if: github.event.pull_request.merged == true
    name: Start Containers
    needs: cd
    uses: ./.github/workflows/start.yml
    secrets:
      IP01: ${{ secrets.IP01 }}
      IP02: ${{ secrets.IP02 }}
      IP03: ${{ secrets.IP03 }}
      IP04: ${{ secrets.IP04 }}
      IP05: ${{ secrets.IP05 }}
      IP06: ${{ secrets.IP06 }}
      IP07: ${{ secrets.IP07 }}
      IP08: ${{ secrets.IP08 }}
      IP09: ${{ secrets.IP09 }}
      IP10: ${{ secrets.IP10 }}
      IP11: ${{ secrets.IP11 }}
      IP12: ${{ secrets.IP12 }}
      IP13: ${{ secrets.IP13 }}
      IP14: ${{ secrets.IP14 }}
      IP15: ${{ secrets.IP15 }}
      NODE_USER: ${{ secrets.NODE_USER }}
      TELEPORT_HOST: ${{ secrets.TELEPORT_HOST }}
      TELEPORT_USER: ${{ secrets.TELEPORT_USER }}
      TELEPORT_PRIVATE_KEY: ${{ secrets.TELEPORT_PRIVATE_KEY }}
      TELEPORT_PORT: ${{ secrets.TELEPORT_PORT }}
