# ---------------------------------
# Workflow for devnet & public-devnet
# ---------------------------------
name: Network Upgrade

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      target:
        description: "Select target environment"
        required: false
        type: choice
        default: devnet
        options:
          - public-devnet
          - devnet
      deployment_option:
        description: "Choose deployment type"
        required: false
        type: choice
        default: Full_Deployment
        options:
          - Quick_Deployment
          - Full_Deployment
          - Genesis_Update_Only
          - Config_Update_Only
      clean_db:
        description: 'Clean database before deployment'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  BRANCH_NAME: ${{ github.ref_name }}

# ---------------------------------
# Continuous Integration (CI)
# ---------------------------------
jobs:

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# ---------------------------------
# Build & Push Docker Image
# ---------------------------------
  publish_image:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          logout: true

      - name: Build & Push moipod container image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          file: ./docker/moipod/internal.amd64
          tags: ghcr.io/sarvalabs/moipod:latest
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}

# ---------------------------------
# Ansible Deploy
# ---------------------------------
  ansible_deploy:
    name: Ansible Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target || 'devnet' }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Deployment Variables
        run: |
          echo "TARGET=${{ github.event.inputs.target || 'devnet' }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_OPTION=${{ github.event.inputs.deployment_option || 'Full_Deployment' }}" >> $GITHUB_ENV
          echo "CLEAN_DB=${{ github.event.inputs.clean_db || 'true' }}" >> $GITHUB_ENV

      - name: Set environment-specific variables
        run: |
          if [[ "$TARGET" == "public-devnet" ]]; then
            echo "TP_TOKEN=github-join-token" >> $GITHUB_ENV
            echo "TP_VERSION=16.2.1" >> $GITHUB_ENV
            echo "S3_BUCKET=pub-devnet-config-template" >> $GITHUB_ENV
            echo "INVENTORY=${{ vars.PUBLIC_DEVNET_NODE_INVENTORY_FILE }}" >> $GITHUB_ENV
          else
            echo "TP_TOKEN=github-ci-token" >> $GITHUB_ENV
            echo "TP_VERSION=16.5.15" >> $GITHUB_ENV
            echo "S3_BUCKET=devnet-config-template" >> $GITHUB_ENV
            echo "INVENTORY=${{ vars.DEVNET_NODE_INVENTORY_FILE_UPDATED }}" >> $GITHUB_ENV
          fi

      - name: Install Teleport CLI
        uses: teleport-actions/setup@v1
        with:
          version: ${{ env.TP_VERSION }}

      - name: Authenticate via Teleport Machine ID
        uses: teleport-actions/auth@v2
        with:
          proxy: ${{ vars.TP_PROXY }}
          token: ${{ env.TP_TOKEN }}
          certificate-ttl: 2h
          anonymous-telemetry: 1

      - name: Run Ansible Playbook
        run: |
          set -e

          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}"

          aws s3 cp s3://$S3_BUCKET/config_template.json.j2 /tmp/config_template.json.j2

          echo "$INVENTORY" | base64 -d > /tmp/node.yml

          MACHINE_ID_DIR=$(find /home/runner/work/_temp -name "ssh_config" -type f -exec dirname {} \; | head -1)

          # Common Ansible config
          cat > /tmp/ansible.cfg <<EOF
          [defaults]
          host_key_checking = False
          inventory = /tmp/node.yml
          remote_tmp = /tmp/.ansible-${USER}/tmp
          pipelining = True
          EOF

          # Conditional differences
          if [[ "$TARGET" == "public-devnet" ]]; then

          echo "forks = 10" >> /tmp/ansible.cfg
          cat >> /tmp/ansible.cfg <<EOF
          [ssh_connection]
          scp_if_ssh = True
          ssh_args = -o ProxyCommand="tsh proxy ssh %h" -o IdentityFile="$MACHINE_ID_DIR/key" -o CertificateFile="$MACHINE_ID_DIR/key-cert.pub" -o ControlMaster=auto -o ControlPersist=600
          EOF

          else

          echo "forks = 15" >> /tmp/ansible.cfg
          echo "callbacks_enabled = profile_tasks" >> /tmp/ansible.cfg
          echo "task_output_limit = 30" >> /tmp/ansible.cfg
          cat >> /tmp/ansible.cfg <<EOF
          [ssh_connection]
          scp_if_ssh = True
          ssh_args = -F $MACHINE_ID_DIR/ssh_config -o ControlMaster=auto -o ControlPersist=480s -o ControlPath=/tmp/ansible-ssh-%r@%h:%p
          EOF

          fi

          ANSIBLE_CONFIG=/tmp/ansible.cfg ansible-playbook \
            ansible-devnet/network-upgrade.yaml \
            -f 15 \
            -e "ansible_remote_tmp=/tmp/.ansible-moichain/tmp" \
            --extra-vars "deployment_option=${{ env.DEPLOYMENT_OPTION }} SUDO_PASSWORD=${{ secrets.SUDO_PASSWORD }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} clean_db=${{ env.CLEAN_DB }} ghcr_pat=${{ secrets.ACCESS_TOKEN }} ghcr_user=${{ secrets.GH_USER }}"