name: Start Containers 

on:  
  workflow_dispatch:
  workflow_call:
    secrets:
      IP01:
        required: true
      IP02:
        required: true
      IP03:
        required: true
      IP04:
        required: true
      IP05:
        required: true
      IP06:
        required: true
      IP07:
        required: true
      IP08:
        required: true
      IP09:
        required: true
      IP10:
        required: true
      IP11:
        required: true
      IP12:
        required: true
      IP13:
        required: true
      IP14:
        required: true
      NODE_USER:
        required: true
      TELEPORT_HOST:
        required: true
      TELEPORT_USER:
        required: true
      TELEPORT_PRIVATE_KEY:
        required: true
      TELEPORT_PORT:
        required: true

jobs:
  start-containers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host: 
          - IP01
          - IP02
          - IP03
          - IP04
          - IP05
          - IP06
          - IP07
          - IP08
          - IP09
          - IP10
          - IP11
          - IP12
          - IP13
          - IP14
    steps:
      - name: Start Devnet
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        with:
          host: ${{ secrets.TELEPORT_HOST }}
          username: ${{ secrets.TELEPORT_USER }}
          key: ${{ secrets.TELEPORT_PRIVATE_KEY }}
          port: ${{ secrets.TELEPORT_PORT }}
          script: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/teleport moichain@${{ secrets[matrix.host] }} "bash start.sh"