name: Stop Containers

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      IP01:
        required: true
      IP02:
        required: true
      IP03:
        required: true
      IP04:
        required: true
      IP05:
        required: true
      IP06:
        required: true
      IP07:
        required: true
      IP08:
        required: true
      IP09:
        required: true
      IP10:
        required: true
      IP11:
        required: true
      IP12:
        required: true
      IP13:
        required: true
      IP14:
        required: true
      NODE_USER:
        required: true
      SSH_KEY:
        required: true
      SSH_PORT:
        required: true
      PROXY_HOST:
        required: true
      PROXY_USER:
        required: true
      PROXY_KEY:
        required: true
      PROXY_PORT:
        required: true

jobs:
  stop-containers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hosts: [HOST01, HOST02, HOST03, HOST04, HOST05, HOST06, HOST07, HOST08, HOST09, HOST10, HOST11, HOST12, HOST13, HOST14]
        include:
          - hosts: HOST01
            ip: IP01
          - hosts: HOST02
            ip: IP02
          - hosts: HOST03
            ip: IP03
          - hosts: HOST04
            ip: IP04
          - hosts: HOST05
            ip: IP05
          - hosts: HOST06
            ip: IP06
          - hosts: HOST07
            ip: IP07
          - hosts: HOST08
            ip: IP08
          - hosts: HOST09
            ip: IP09
          - hosts: HOST10
            ip: IP10
          - hosts: HOST11
            ip: IP11
          - hosts: HOST12
            ip: IP12
          - hosts: HOST13
            ip: IP13
          - hosts: HOST14
            ip: IP14
    steps:
      - name: Stop Devnet
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        with:
          host: ${{ secrets[matrix.ip] }}
          username: ${{ secrets.NODE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USER }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: bash stop.sh
