name: Network Upgrade Devnet
on:

  workflow_dispatch:
    inputs:
      environment:
          default: 'Quick_Deployment'
          description: 'Choose deployment option'
          required: true
          type: choice
          options:
            - Quick_Deployment
            - Full_Deployment
            - Genesis_Update_Only
            - Config_Update_Only   
            

env: 
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.0.0

      - name: Login to Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          logout: true

      - name: Build, & Push moipod container image ( pr_merge_event )
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          push: true
          file: ./docker/moipod/internal.amd64
          tags: "ghcr.io/sarvalabs/moipod:latest"
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}

  ansible-playbook:
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set deployment option as an environment variable
      - name: Set Deployment Option
        id: set_option
        run: |
          echo "DEPLOYMENT_OPTION=${{ github.event.inputs.environment }}" >> $GITHUB_ENV


      # Step 3: Connect to the jump server and execute the playbook
      - name: Run Ansible Playbook on Jump Server
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        with:
          host: ${{ secrets.TELEPORT_HOST }}
          username: ${{ secrets.TELEPORT_USER }}
          key: ${{ secrets.TELEPORT_PRIVATE_KEY }}
          port: ${{ secrets.TELEPORT_PORT }}
          script: |
            echo "Starting playbook execution..."
            cd /home/github/go-moi
            echo ${{ github.ref_name }}
            echo "Pulling latest changes from branch: ${{ github.ref_name }}"
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            # Export AWS credentials as environment variables
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            export SUDO_PASSWORD=${{ secrets.SUDO_PASSWORD }}
            # Run the Ansible playbook with extra vars based on deployment option
            ansible-playbook -i ansible-playbooks/inventory-devnet.yml ansible-playbooks/upgrade.yaml -f 10 \
            --extra-vars "ansible_ssh_private_key_file=/home/github/.ssh/id_rsa" \
            -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} deployment_option=${{ env.DEPLOYMENT_OPTION }} SUDO_PASSWORD=${{ secrets.SUDO_PASSWORD }}"
