all:
  children:
    devnet-servers:
      hosts:
        devnet-node-test-1:
          ansible_host: 95.217.177.48
          ansible_ssh_user: moichain
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

        devnet-node-test-2:
          ansible_host: 65.108.222.234
          ansible_ssh_user: moichain
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

      vars:
          base_port: 6000  # Starting port for devnet-node-1
          base_prometheus_port: 30000  # Starting port for Prometheus
          base_jsonrpc_port: 1600  # Starting port for JSON-RPC
          bootnode_endpoint: "/ip4/95.216.156.216/tcp/4005/p2p/16Uiu2HAm7HVPt5uTkNWYJQexpxXfQPkJwd9TnWua3eqFihWUNZmu"
          s3_bucket_genesis: "genesis-devnet"
          s3_file_genesis: "genesis.json"
          local_temp_path_genesis: "/home/moichain/genesis.json"
          target_path_genesis: "/home/moichain/shared/moipod/genesis.json"
          image_tag: "latest"
          operator_slot: 1
          validator_slot: 3
          clean_db: "true"
          allow_origin: "*"
          node_password: "test123"
          discovery_interval: "1m0s"
          log_level: "TRACE"

   
    devnet-backup-servers:
      hosts:
        devnet-node-test-1:
          ansible_host: 95.217.177.48
          ansible_ssh_user: moichain
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

        devnet-node-test-2:
          ansible_host: 65.108.222.234
          ansible_ssh_user: moichain
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

      vars:
          backup_dir: "/home/moichain/backup"
          aws_bucket: "backup-devnet-bootnode"
          directories_to_backup:
            - { name: "test_0", path: "/home/moichain/shared/moipod/test_0" }
            - { name: "test_1", path: "/home/moichain/shared/moipod/test_1" }
                                      
    bootnode-server:
      hosts:  
       bootnode-server:
          ansible_host: 95.216.156.216
          ansible_ssh_user: root 
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

      vars:
             backup_dir: "/root/backup"
             aws_bucket: "backup-devnet-bootnode"
             directories_to_backup:
             - { name: "bg-node1", path: "/root/bg-node1" }
             - { name: "bg-node2", path: "/root/bg-node2" }
             - { name: "bg-node3", path: "/root/bg-node3" }
             - { name: "bg-node4", path: "/root/bg-node4" }
             - { name: "bootnode", path: "/root/bootnode" }

